export const UPDATE_QUERY = 'YOUTUBE_SEARCH:UPDATE_QUERY';
export const SEND_SEARCH_QUERY = 'YOUTUBE_SEARCH:SEND_SEARCH_QUERY';
export const RECEIVE_SEARCH_RESULTS = 'YOUTUBE_SEARCH:RECEIVE_SEARCH_RESULTS';
