export const UPDATE_QUERY = 'YOUTUBE_SEARCH:UPDATE_QUERY';
export const SEND_SEARCH_QUERY = 'YOUTUBE_SEARCH:SEND_SEARCH_QUERY';
export const RECEIVE_SEARCH_RESULTS = 'YOUTUBE_SEARCH:RECEIVE_SEARCH_RESULTS';

export const PAGE_CHANGE_REQUEST = 'YOUTUBE_SEARCH:PAGE_CHANGE_REQUEST';
export const PAGE_CHANGE_RESPONSE = 'YOUTUBE_SEARCH:PAGE_CHANGE_RESPONSE';

// Login related contants
export const LOGIN_REQUESTED = 'YOUTUBE_SEARCH:LOGIN_REQUESTED';
export const LOGIN_RECEIVED = 'YOUTUBE_SEARCH:LOGIN_RECEIVED';
export const LOGIN_FAILED = 'YOUTUBE_SEARCH:LOGIN_FAILED';

// Logout related constants
export const LOGOUT_REQUESTED = 'YOUTUBE_SEARCH:LOGOUT_REQUESTED';
export const LOGOUT_RECEIVED = 'YOUTUBE_SEARCH:LOGOUT_RECEIVED';

export const CLEAR_VIDEOS = 'YOUTUBE_SEARCH:CLEAR_VIDEOS';
