export const UPDATE_QUERY = 'YOUTUBE_SEARCH:UPDATE_QUERY';
export const SEARCH_REQUESTED = 'YOUTUBE_SEARCH:SEARCH_REQUESTED';
export const SEARCH_RECEIVED = 'YOUTUBE_SEARCH:SEARCH_RECEIVED';

export const PAGE_CHANGE_REQUESTED = 'YOUTUBE_SEARCH:PAGE_CHANGE_REQUESTED';
export const PAGE_CHANGE_RECEIVED = 'YOUTUBE_SEARCH:PAGE_CHANGE_RECEIVED';

// Login related contants
export const LOGIN_REQUESTED = 'YOUTUBE_SEARCH:LOGIN_REQUESTED';
export const LOGIN_RECEIVED = 'YOUTUBE_SEARCH:LOGIN_RECEIVED';
export const LOGIN_FAILED = 'YOUTUBE_SEARCH:LOGIN_FAILED';

// Logout related constants
export const LOGOUT_REQUESTED = 'YOUTUBE_SEARCH:LOGOUT_REQUESTED';
export const LOGOUT_RECEIVED = 'YOUTUBE_SEARCH:LOGOUT_RECEIVED';

export const CLEAR_VIDEOS = 'YOUTUBE_SEARCH:CLEAR_VIDEOS';

export const ERROR_RECEIVED = 'YOUTUBE_SEARCH:ERROR_RECEIVED';
