# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='preview_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
